const allowedTypes = new Set(['image/jpeg','image/png','image/webp','application/pdf','video/mp4','video/webm']);
const maxBytes = 100 * 1024 * 1024;
const enc = new TextEncoder();

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function slug(v=''){return v.toLowerCase().trim().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)||'item'}
function cookieValue(request,name){const raw=request.headers.get('cookie')||'';for(const part of raw.split(';')){const [k,...rest]=part.trim().split('=');if(k===name)return rest.join('=')}return''}
async function sessionValue(secret){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,enc.encode('woodrick-admin-session-v1'));return Array.from(new Uint8Array(sig)).map(b=>b.toString(16).padStart(2,'0')).join('')}
async function isAdmin(request,env){if(!env.ADMIN_UPLOAD_TOKEN)return false;return cookieValue(request,'woodrick_admin')===await sessionValue(env.ADMIN_UPLOAD_TOKEN)}
async function authorized(request,env){const auth=request.headers.get('authorization')||'';return (!!env.ADMIN_UPLOAD_TOKEN&&auth===`Bearer ${env.ADMIN_UPLOAD_TOKEN}`)||await isAdmin(request,env)}
function loginPage(error=''){return new Response(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Woodrick Homes Admin Login</title><style>body{margin:0;background:#080808;color:#fff;font-family:Arial,sans-serif;display:grid;place-items:center;min-height:100vh}.box{width:min(420px,90%);border:2px solid #f0c96b;background:#111;padding:30px;box-shadow:0 20px 60px #000}.brand{color:#f0c96b;font-weight:900;letter-spacing:2px;margin-bottom:18px}h1{font-family:Georgia,serif;font-weight:500;margin:0 0 10px;font-size:38px}p{color:#bbb;line-height:1.6}input{width:100%;box-sizing:border-box;padding:14px;margin:12px 0;border:1px solid #777;background:#fff;font-size:16px}button{width:100%;padding:14px;background:#f0c96b;border:0;font-weight:900;cursor:pointer}.err{color:#ffb0b0;margin-top:8px}</style></head><body><form class="box" method="post" action="/admin-login"><div class="brand">WOODRICK HOMES</div><h1>Admin Login</h1><p>Authorised staff only. Enter the admin access code to continue.</p><input type="password" name="password" autocomplete="current-password" required autofocus><button type="submit">LOGIN</button>${error?`<div class="err">${error}</div>`:''}</form></body></html>`,{status:error?401:200,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-robots-tag':'noindex, nofollow'}})}
async function handleLogin(request,env){if(!env.ADMIN_UPLOAD_TOKEN)return loginPage('Admin login is not configured.');const form=await request.formData();const password=String(form.get('password')||'');if(password!==env.ADMIN_UPLOAD_TOKEN)return loginPage('Invalid admin access code.');const value=await sessionValue(env.ADMIN_UPLOAD_TOKEN);return new Response(null,{status:303,headers:{location:'/admin-products/','set-cookie':`woodrick_admin=${value}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800`,'cache-control':'no-store'}})}
function handleLogout(){return new Response(null,{status:303,headers:{location:'/admin-products/','set-cookie':'woodrick_admin=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0','cache-control':'no-store'}})}

async function handleMedia(request,env){if(!env.PRODUCT_MEDIA)return json({error:'PRODUCT_MEDIA R2 binding is missing'},500);try{const url=new URL(request.url),key=url.searchParams.get('key');if(key){const obj=await env.PRODUCT_MEDIA.get(key);if(!obj)return new Response('Not found',{status:404});const headers=new Headers();obj.writeHttpMetadata(headers);headers.set('etag',obj.httpEtag);headers.set('cache-control','public, max-age=3600');return new Response(obj.body,{headers})}const listed=await env.PRODUCT_MEDIA.list({limit:100,include:['customMetadata']});const items=listed.objects.map(o=>({key:o.key,size:o.size,uploaded:o.uploaded,...(o.customMetadata||{})})).sort((a,b)=>String(b.uploadedAt||b.uploaded).localeCompare(String(a.uploadedAt||a.uploaded)));return json({items,truncated:listed.truncated})}catch(err){return json({error:`Media API error: ${err&&err.message?err.message:'Unknown error'}`},500)}}
async function handleUpload(request,env){if(!env.PRODUCT_MEDIA)return json({error:'PRODUCT_MEDIA R2 binding is missing'},500);if(!await authorized(request,env))return json({error:'Admin login required'},401);try{const form=await request.formData(),file=form.get('file'),category=String(form.get('category')||'').trim(),type=String(form.get('type')||'').trim(),title=String(form.get('title')||'').trim();if(!file||typeof file.arrayBuffer!=='function')return json({error:'Please select a file'},400);if(!category||!title)return json({error:'Category and title are required'},400);if(!allowedTypes.has(file.type))return json({error:'Unsupported file type'},415);if(file.size>maxBytes)return json({error:'File is too large. Maximum size is 100 MB.'},413);const ext=(file.name.split('.').pop()||'bin').toLowerCase().replace(/[^a-z0-9]/g,''),key=`${slug(category)}/${type}/${Date.now()}-${slug(title)}.${ext}`,meta={category,title,type,originalName:file.name,uploadedAt:new Date().toISOString()},body=await file.arrayBuffer();await env.PRODUCT_MEDIA.put(key,body,{httpMetadata:{contentType:file.type||'application/octet-stream'},customMetadata:meta});return json({ok:true,key,category,title,type,url:`/api/media?key=${encodeURIComponent(key)}`},201)}catch(err){return json({error:`Upload API error: ${err&&err.message?err.message:'Unknown error'}`},500)}}
async function handleDelete(request,env){if(!env.PRODUCT_MEDIA)return json({error:'PRODUCT_MEDIA R2 binding is missing'},500);if(!await authorized(request,env))return json({error:'Admin login required'},401);try{const data=await request.json(),key=String(data&&data.key||'').trim();if(!key)return json({error:'Media key is required'},400);const existing=await env.PRODUCT_MEDIA.head(key);if(!existing)return json({error:'Media file not found'},404);await env.PRODUCT_MEDIA.delete(key);return json({ok:true,key})}catch(err){return json({error:`Delete API error: ${err&&err.message?err.message:'Unknown error'}`},500)}}
async function serveAssetWithAppEnhancements(request,env,url){if(!env.ASSETS||typeof env.ASSETS.fetch!=='function')return json({error:'Static assets binding is unavailable'},500);const response=await env.ASSETS.fetch(request);if(request.method!=='GET')return response;const contentType=response.headers.get('content-type')||'';if(!contentType.includes('text/html'))return response;let html=await response.text();const pwaHead=`\n<link rel="manifest" href="/manifest.webmanifest">\n<meta name="theme-color" content="#0b0b0b">\n<meta name="mobile-web-app-capable" content="yes">\n<meta name="apple-mobile-web-app-capable" content="yes">\n<meta name="apple-mobile-app-status-bar-style" content="black-translucent">\n<meta name="apple-mobile-web-app-title" content="Woodrick Homes">\n<link rel="icon" href="/app-icon.svg" type="image/svg+xml">`;if(!html.includes('rel="manifest"'))html=html.includes('</head>')?html.replace('</head>',pwaHead+'\n</head>'):pwaHead+html;const swRegistration=`\n<script>if('serviceWorker'in navigator){window.addEventListener('load',function(){navigator.serviceWorker.register('/sw.js').catch(function(){})})</script>`;if(!html.includes("navigator.serviceWorker.register('/sw.js')"))html=html.includes('</body>')?html.replace('</body>',swRegistration+'\n</body>'):html+swRegistration;const productLinkFix=`\n<script>window.addEventListener('DOMContentLoaded',function(){var navProduct=document.querySelector('.menu a[href="#products-services"]');if(navProduct)navProduct.href='/products/';var heroProduct=document.querySelector('.hero-actions a[href="#products-services"]');if(heroProduct)heroProduct.href='/products/';var productTab=document.querySelector('[data-tab="ws-products"]');if(productTab){productTab.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();window.location.href='/products/';},true);}});</script>`;if(url.pathname==='/'||url.pathname==='/index.html'){html=html.includes('</body>')?html.replace('</body>',productLinkFix+'\n</body>'):html+productLinkFix;const mobileBrightness=`\n<style id="woodrick-bright-hero-2026">
body{background:#fffdf8}
.topbar{background:#f6efe4!important;color:#5d4937!important;border-bottom:1px solid #eadfcf!important}
.topbar .container{color:#5d4937!important}
.nav{background:#fffdf9!important;color:#2e241d!important;border-top:0!important;border-bottom:1px solid #e7dccb!important;box-shadow:0 8px 26px rgba(93,69,43,.08)!important}
.nav-inner{background:#fffdf9!important;border:0!important;border-radius:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
.nav .logo{color:#2d2119!important;text-shadow:none!important}.nav .logo span{color:#2d2119!important}.nav .logo small{color:#b18445!important}.nav .logo-mark{background:#fffaf1!important;color:#b18445!important;border:2px solid #b18445!important;box-shadow:none!important}
.nav .menu a{color:#3d3128!important;text-shadow:none!important;font-weight:700!important}.nav .menu a:hover,.nav .menu a:focus-visible,.nav .menu a.active{color:#b18445!important}.nav .menu a:after{background:#c49a55!important}
.nav .btn-gold{background:#c7963e!important;color:#fff!important;border:1px solid #c7963e!important;box-shadow:0 8px 20px rgba(183,138,59,.18)!important}.nav .btn-gold:hover{background:#aa7727!important}
.mobile-menu{color:#9c7338!important}
.hero{min-height:780px!important;color:#2f251f!important;background:linear-gradient(90deg,rgba(255,253,248,.98) 0%,rgba(255,253,248,.94) 31%,rgba(255,253,248,.70) 49%,rgba(255,253,248,.10) 72%),url('https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=2200&q=92') center/cover!important}
.hero:after{background:linear-gradient(180deg,rgba(255,255,255,0) 70%,rgba(255,250,242,.36))!important}
.hero-content{padding-top:225px!important;max-width:700px!important}.hero .kicker{color:#9a6b32!important;background:#fffaf1!important;border:1px solid #d8b66f!important;box-shadow:0 4px 16px rgba(173,133,65,.08)!important}.hero h1{color:#2f241d!important;text-shadow:none!important;font-size:clamp(52px,6vw,80px)!important;line-height:1.01!important}.hero h1 em{color:#c08c36!important}.hero p{color:#5e5147!important;text-shadow:none!important;max-width:610px!important}.hero .trust span{color:#6a594a!important}.hero .trust span::before{color:#c08c36!important}.hero .btn-gold{background:#c7963e!important;color:#fff!important;border-color:#c7963e!important}.hero .btn-outline{background:#fffaf3!important;color:#7b5926!important;border-color:#c89b52!important}.hero .btn-outline:hover{background:#f2dfbd!important;color:#4b3520!important}.premium-proof{border-top:1px solid #dcc9aa!important}.premium-proof strong{color:#3f3026!important}.premium-proof small{color:#8a7564!important}
@media(max-width:850px){.nav-inner{background:#fffdf9!important}.nav .menu{background:#fffdf9!important;border-top:1px solid #eadfcf!important;border-bottom:1px solid #eadfcf!important}.nav .menu a{color:#3d3128!important}.hero{min-height:760px!important;background:linear-gradient(90deg,rgba(255,253,248,.96) 0%,rgba(255,253,248,.88) 48%,rgba(255,253,248,.28) 100%),url('https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=1600&q=92') 62% center/cover!important}.hero-content{padding-top:205px!important}.hero h1{font-size:52px!important}.ws-upgrade,.projects,.modular-showcase{background:#fffdf9!important}.testimonials{background:#f8f2e8!important}.feature,.ws-card{background:#fff!important}}
@media(max-width:520px){.hero{min-height:720px!important;background:linear-gradient(90deg,rgba(255,253,248,.96) 0%,rgba(255,253,248,.88) 58%,rgba(255,253,248,.35) 100%),url('https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=1200&q=92') 66% center/cover!important}.hero-content{padding-top:180px!important}.hero h1{font-size:43px!important}.hero p{font-size:15px!important}}
</style>`;html=html.includes('</head>')?html.replace('</head>',mobileBrightness+'\n</head>'):mobileBrightness+html}const adminShortcut=`\n<script>window.addEventListener('DOMContentLoaded',function(){var target=document.querySelector('.footer .logo, .footer [class*="logo"], .footer h2, .footer h3, .footer strong');if(!target)return;var taps=0,timer=null;target.style.cursor='default';target.addEventListener('click',function(e){taps++;clearTimeout(timer);timer=setTimeout(function(){taps=0},1800);if(taps>=5){e.preventDefault();taps=0;window.location.href='/admin-products/';}});});</script>`;if(!url.pathname.startsWith('/admin-')&&!html.includes("taps>=5")){html=html.includes('</body>')?html.replace('</body>',adminShortcut+'\n</body>'):html+adminShortcut}const headers=new Headers(response.headers);headers.delete('content-length');headers.set('cache-control','no-cache');if(url.pathname.startsWith('/admin-products'))headers.set('x-robots-tag','noindex, nofollow');return new Response(html,{status:response.status,statusText:response.statusText,headers})}

export default{async fetch(request,env){try{const url=new URL(request.url);if(url.pathname==='/admin-login'&&request.method==='POST')return handleLogin(request,env);if(url.pathname==='/admin-logout')return handleLogout();if(url.pathname.startsWith('/admin-products')&&!await isAdmin(request,env))return loginPage();if(url.pathname==='/api/media'&&request.method==='GET')return handleMedia(request,env);if(url.pathname==='/api/upload'&&request.method==='POST')return handleUpload(request,env);if(url.pathname==='/api/delete'&&request.method==='POST')return handleDelete(request,env);if((url.pathname==='/api/upload'||url.pathname==='/api/delete')&&request.method==='OPTIONS')return new Response(null,{status:204,headers:{allow:'POST, OPTIONS'}});return serveAssetWithAppEnhancements(request,env,url)}catch(err){return json({error:`Worker error: ${err&&err.message?err.message:'Unknown error'}`},500)}}};